name: Ada (GNAT)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Re-synchronize package indices 
      run: sudo apt-get update

    - name: Set up GNAT toolchain
      run: sudo apt-get -y install gnat gprbuild asis-programs

    - name: Build
      run: gprbuild -j0 -p chess.gpr

    - name: Generate test skeleton
      run: gnattest -dd -P chess.gpr -v -r

    - name: Build test project
      run: gprbuild -p -Ptest/harness/test_driver.gpr

    - name: Run unit tests
      run: test/harness/test_runner --passed-tests=hide --skeleton-default=pass